defaultPlacement: end
enableVersioning: true
entryTypes:
  - a0daecac-4894-4577-9524-d1b7444e901b # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 2ff163d2-aa9a-4973-ab76-40b01ed6032b
type: structure
